### ISSUE TITLE
Domestic Address Nova Field

### ISSUE THREAD

**Issue by drewroberts** [tipoff/addresses#84] opened 2021-03-20 18:13 UTC
We need to implement the Google Places Autocomplete (#30) in Laravel Nova when create a new Domestic Address resource.

**Comment by drewroberts** [comment] 2021-03-27 15:14
I accidentally duplicated this issue. Going to close this one and use that issue: #108

**Comment by devjk1** [comment] 2021-04-21 23:22
@pdbreen We are having trouble creating a custom nova field.  We ran `php artisan nova:field tipoff/nova-domestic-address` and then transferred those files from Demo into the Tipoff/Addresses package & updated composer.json and ran 'composer update' in Demo.  

```
vagrant@homestead:~/code/tipoff/demo$ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tipoff/addresses[dev-omnia/feature/84_domestic_address_nova_field, dev-main] require tipoff/nova-domestic-address * -> could not be found in any version, there may be a typo in the package name.
    - Root composer.json requires tipoff/addresses * -> satisfiable by tipoff/addresses[dev-omnia/feature/84_domestic_address_nova_field, dev-main].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

```
Addresses pkg composer.json
![image](https://user-images.githubusercontent.com/62731054/115632783-7ab02f80-a2d6-11eb-8b78-00f8738aa0a0.png)
![image](https://user-images.githubusercontent.com/62731054/115632842-987d9480-a2d6-11eb-8dee-525644ad2e95.png)
composer.json inside /nova-components/NovaDomesticAddress
![image](https://user-images.githubusercontent.com/62731054/115633220-b0edaf00-a2d6-11eb-88a8-c816f73d65a3.png)

**Comment by pdbreen** [comment] 2021-04-22 12:41
@devjk1 it looks like you need to `composer remove tipoff/nova-domestic-address` (or manually delete that line from composer.json) in tipoff/addresses package.  It sounds like the nova component is in the addresses package, not a different one.

**Comment by devjk1** [comment] 2021-04-22 20:47
@pdbreen Could you push an example with a 'custom nova field' to this Addresses package.  Getting started presents a bigger problem than anticipated.
https://nova.laravel.com/docs/3.0/customization/fields.html

**Comment by pdbreen** [comment] 2021-04-23 14:33
@devjk1 @drewroberts  I'm confused. PR  #140  added google places autocomplete by pulling in a 3rd party nova package - https://github.com/tipoff/addresses/blob/d1918fbdbf838c5392dc0b90ae7780097227c422/composer.json#L19

Is this issue now resolved?  or, this there still a desire to create a custom tipoff field?

**Comment by devjk1** [comment] 2021-04-23 15:14
@pdbreen  Hi Patrick, the issue is not resolved yet.  Drew wants to reuse the DomesticAddress/Phone JS components in custom Nova fields, instead of using the emiliano pkg.
If we create a standalone package using the standard `php artisan nova:field pkg/component`, then the Addresses pkg would require the nova-field, but also provide requirements (JS component) to the nova-field.

**Comment by pdbreen** [comment] 2021-04-23 16:12
@devjk1 I've added #145 that you should take over to complete the actual field implementation.

**Comment by joshtorres** [comment] 2021-04-30 08:03
This is completed

**Closed by joshtorres** 2021-04-30 08:03 UTC
