### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by arwaawan3** [tipoff/addresses#149] opened 2021-04-27 23:24 UTC
- timezone drop down not pulling up results in City add/edit page
- Unable to attach city to zip, or vice versa, city/zip dropdowns don't have results
- Attach city/zip 'primary' field error - incorrect value true/false should 1/0
- Add fields to country nova resource
- Unique validation on state, country nova resource fields
- Country calling code index, search by country
- fix city fieldsforindex
- cannot add/edit country callingcode, missing root and suffix fields
- fix phone area sort by state
- add missing fields to zip nova resource, including parent_zip_code relationship
- search by state in zips index
- search by country in states index
- remove creator/updater traits from Timezones model (TBD - alternatively should we add them to the migration and nova resource)

**Comment by chx2** [comment] 2021-04-27 23:34
@arwaawan3 is this a duplicate of https://github.com/tipoff/addresses/issues/143?

**Comment by arwaawan3** [comment] 2021-04-27 23:49
@chx2 Yes, I didn't see that one already existed. I'm also discovering some other issues that I will add on here.

**Closed** 2021-04-30 07:31 UTC
